name: bike_rental_pos
description: A POS application for bike rental by the hour
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  flutter_launcher_icons: ^0.14.3 # تحديث الإصدار إلى النسخة الأخيرة المتوافقة
  # UI Components
  cupertino_icons: ^1.0.2
  curved_navigation_bar: ^1.0.3

  # State Management
  provider: ^6.0.5
  flutter_bloc: ^8.1.3
  equatable: ^2.0.5

  # Storage & Data
  shared_preferences: ^2.2.2
  sqflite: ^2.3.0
  path: ^1.9.0
  path_provider: ^2.1.1
  flutter_secure_storage: ^9.0.0

  # Utilities
  sunmi_printer_plus: ^4.1.0
  intl: ^0.19.0
  uuid: ^4.2.2
  pdf: ^3.10.7
  printing: ^5.11.1
  flutter_rating_bar: ^4.0.1
  fl_chart: ^0.66.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/images/logo.png

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/images/img.png"
